name: Mott the Tidier
on:
  pull_request:
    types: [ labeled ]

jobs:
  mod_cleaner:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    runs-on: ubuntu-latest
    name: Clean up dependabot mods to go.sum files
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'
    - uses: evantorrie/mott-the-tidier@v1-beta
      id: modtidy
      with:
        files: '**/go.mod'
        gosum_only: true
    - name: commit changes
      id: autocommit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-fix go.sum changes caused by dependabot
    - name: Show changes
      run: |
        echo "Changes detected: ${{ steps.autocommit.outputs.changes_detected }}"
