name: 'Request reviews from code owners of a PR'
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - ready_for_review

permissions:
  contents: read

jobs:
  request_codeowners_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ github.repository_owner == 'open-telemetry' && github.event.pull_request.draft == false }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run request_codeowners_review.sh
        run: ./tools/request_codeowners_review.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.number }}
